//
// Generated file, do not edit! Created by opp_msgtool 6.2 from Request.msg.
//

#ifndef __REQUEST_M_H
#define __REQUEST_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Request;
/**
 * Class generated from <tt>Request.msg:19</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet Request
 * {
 *     double R;
 *     double D;
 *     bool type; // 0 container-based     1 Faas
 * }
 * </pre>
 */
class Request : public ::omnetpp::cPacket
{
  protected:
    double R = 0;
    double D = 0;
    bool type = false;

  private:
    void copy(const Request& other);

  protected:
    bool operator==(const Request&) = delete;

  public:
    Request(const char *name=nullptr, short kind=0);
    Request(const Request& other);
    virtual ~Request();
    Request& operator=(const Request& other);
    virtual Request *dup() const override {return new Request(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual double getR() const;
    virtual void setR(double R);

    virtual double getD() const;
    virtual void setD(double D);

    virtual bool getType() const;
    virtual void setType(bool type);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Request& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Request& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Request *fromAnyPtr(any_ptr ptr) { return check_and_cast<Request*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __REQUEST_M_H

